version: 1
module_version: 6.1.2

test_defaults:
  runner_image: 851725245549.dkr.ecr.us-east-2.amazonaws.com/mdlz-spacelift:latest
tests:
  - name: Simple AWS API gateway test
    project_root: examples/simple
